dubbo:
  application:
    name: web-search
  registry:
    protocol: zookeeper
    address: 192.168.142.137:2181
server:
  port: 9092
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.142.137
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907




