dubbo:
  application:
    name: web-center
  registry:
    protocol: zookeeper
    address: 192.168.142.137:2181
server:
  port: 9090
spring:
  thymeleaf:
    cache: false

#上传文件
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 10.36.8.8:22122




