dubbo:
  application:
    name: sms-service
  registry:
    protocol: zookeeper
    address: 192.168.142.137:2181
  protocol:
    port: 28813

spring:
  rabbitmq:
    host: 192.168.142.137
    port: 5672
    username: java1907
    password: 123
    virtual-host: /java1907